# CASE_STUDY

In [2]:
import pandas as pd
data = pd.read_csv("/content/employee_managment_system.csv")
df = pd.DataFrame(data)
print(df)

    Employee_ID            Name  Age  Gender Department    City  Experience  \
0          1001    Aarav Sharma   25    Male         IT  Indore           2
1          1002     Priya Singh   28  Female         HR  Bhopal           5
2          1003     Rahul Verma   30    Male    Finance  Indore           7
3          1004    Ananya Patel   24  Female         IT    Pune           1
4          1005    Vikram Joshi   32    Male      Sales  Mumbai           8
5          1006      Neha Gupta   27  Female         IT  Indore           4
6          1007     Rohan Mehta   29    Male         HR   Delhi           6
7          1008     Isha Kapoor   26  Female  Marketing    Pune           3
8          1009  Karan Malhotra   35    Male    Finance  Mumbai          10
9          1010      Meera Shah   31  Female         IT  Bhopal           7
10         1011      Aditya Rao   23    Male      Sales  Indore           1
11         1012      Sneha Jain   28  Female  Marketing   Delhi           5
12         1013      Arjun Nair   33    Male         IT    Pune           9
13         1014    Kavya Mishra   26  Female         HR  Bhopal           3
14         1015    Manish Yadav   37    Male    Finance   Delhi          12
15         1016   Pooja Agarwal   29  Female      Sales  Mumbai           6
16         1017      Sahil Khan   24    Male  Marketing  Indore           2
17         1018        Riya Das   32  Female         IT   Delhi           8
18         1019      Mohit Soni   27    Male      Sales    Pune           4
19         1020       Tanya Roy   30  Female    Finance  Bhopal           7

    Salary  Performance_Score  Attendance  Projects    Status
0    45000                 78          92         3    Active
1    55000                 85          95         4    Active
2    72000                 88          89         5    Active
3    40000                 72          90         2    Active
4    68000                 76          84         6    Active
5    62000                 91          97         5    Active
6    58000                 69          78         3  Inactive
7    50000                 82          93         4    Active
8    90000                 94          91         7    Active
9    78000                 89          96         6    Active
10   38000                 65          74         2  Inactive
11   61000                 87          88         5    Active
12   85000                 93          94         7    Active
13   48000                 75          86         3    Active
14   98000                 90          87         8    Active
15   64000                 81          90         5    Active
16   43000                 70          82         3    Active
17   82000                 95          98         7    Active
18   52000                 74          85         4    Active
19   76000                 86          93         6    Active

# **PANDAS BASICS**

In [ ]:
df.head()

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
0,1001,Aarav Sharma,25,Male,IT,Indore,2,45000,78,92,3,Active
1,1002,Priya Singh,28,Female,HR,Bhopal,5,55000,85,95,4,Active
2,1003,Rahul Verma,30,Male,Finance,Indore,7,72000,88,89,5,Active
3,1004,Ananya Patel,24,Female,IT,Pune,1,40000,72,90,2,Active
4,1005,Vikram Joshi,32,Male,Sales,Mumbai,8,68000,76,84,6,Active

In [ ]:
df.tail()

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
15,1016,Pooja Agarwal,29,Female,Sales,Mumbai,6,64000,81,90,5,Active
16,1017,Sahil Khan,24,Male,Marketing,Indore,2,43000,70,82,3,Active
17,1018,Riya Das,32,Female,IT,Delhi,8,82000,95,98,7,Active
18,1019,Mohit Soni,27,Male,Sales,Pune,4,52000,74,85,4,Active
19,1020,Tanya Roy,30,Female,Finance,Bhopal,7,76000,86,93,6,Active

In [ ]:
df.shape

(20, 12)

In [ ]:
df.columns

Index(['Employee_ID', 'Name', 'Age', 'Gender', 'Department', 'City',
       'Experience', 'Salary', 'Performance_Score', 'Attendance', 'Projects',
       'Status'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        20 non-null     int64
 1   Name               20 non-null     object
 2   Age                20 non-null     int64
 3   Gender             20 non-null     object
 4   Department         20 non-null     object
 5   City               20 non-null     object
 6   Experience         20 non-null     int64
 7   Salary             20 non-null     int64
 8   Performance_Score  20 non-null     int64
 9   Attendance         20 non-null     int64
 10  Projects           20 non-null     int64
 11  Status             20 non-null     object
dtypes: int64(7), object(5)
memory usage: 2.0+ KB

In [ ]:
df.describe()

,Employee_ID,Age,Experience,Salary,Performance_Score,Attendance,Projects
count,20.00000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000
mean,1010.50000,28.800000,5.500000,63250.000000,82.000000,89.100000,4.750000
std,5.91608,3.764096,3.052178,17450.305381,9.124865,6.290343,1.773341
min,1001.00000,23.000000,1.000000,38000.000000,65.000000,74.000000,2.000000
25%,1005.75000,26.000000,3.000000,49500.000000,74.750000,85.750000,3.000000
50%,1010.50000,28.500000,5.500000,61500.000000,83.500000,90.000000,5.000000
75%,1015.25000,31.250000,7.250000,76500.000000,89.250000,93.250000,6.000000
max,1020.00000,37.000000,12.000000,98000.000000,95.000000,98.000000,8.000000

# **SELECTING DATA**

In [ ]:
df[["Name","Department","Salary","Status"]]

              Name Department  Salary    Status
0     Aarav Sharma         IT   45000    Active
1      Priya Singh         HR   55000    Active
2      Rahul Verma    Finance   72000    Active
3     Ananya Patel         IT   40000    Active
4     Vikram Joshi      Sales   68000    Active
5       Neha Gupta         IT   62000    Active
6      Rohan Mehta         HR   58000  Inactive
7      Isha Kapoor  Marketing   50000    Active
8   Karan Malhotra    Finance   90000    Active
9       Meera Shah         IT   78000    Active
10      Aditya Rao      Sales   38000  Inactive
11      Sneha Jain  Marketing   61000    Active
12      Arjun Nair         IT   85000    Active
13    Kavya Mishra         HR   48000    Active
14    Manish Yadav    Finance   98000    Active
15   Pooja Agarwal      Sales   64000    Active
16      Sahil Khan  Marketing   43000    Active
17        Riya Das         IT   82000    Active
18      Mohit Soni      Sales   52000    Active
19       Tanya Roy    Finance   76000    Active

In [ ]:
df[["Name","Experience","Performance_Score"]]

              Name  Experience  Performance_Score
0     Aarav Sharma           2                 78
1      Priya Singh           5                 85
2      Rahul Verma           7                 88
3     Ananya Patel           1                 72
4     Vikram Joshi           8                 76
5       Neha Gupta           4                 91
6      Rohan Mehta           6                 69
7      Isha Kapoor           3                 82
8   Karan Malhotra          10                 94
9       Meera Shah           7                 89
10      Aditya Rao           1                 65
11      Sneha Jain           5                 87
12      Arjun Nair           9                 93
13    Kavya Mishra           3                 75
14    Manish Yadav          12                 90
15   Pooja Agarwal           6                 81
16      Sahil Khan           2                 70
17        Riya Das           8                 95
18      Mohit Soni           4                 74
19       Tanya Roy           7                 86

In [ ]:
df.head(10)

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
0,1001,Aarav Sharma,25,Male,IT,Indore,2,45000,78,92,3,Active
1,1002,Priya Singh,28,Female,HR,Bhopal,5,55000,85,95,4,Active
2,1003,Rahul Verma,30,Male,Finance,Indore,7,72000,88,89,5,Active
3,1004,Ananya Patel,24,Female,IT,Pune,1,40000,72,90,2,Active
4,1005,Vikram Joshi,32,Male,Sales,Mumbai,8,68000,76,84,6,Active
5,1006,Neha Gupta,27,Female,IT,Indore,4,62000,91,97,5,Active
6,1007,Rohan Mehta,29,Male,HR,Delhi,6,58000,69,78,3,Inactive
7,1008,Isha Kapoor,26,Female,Marketing,Pune,3,50000,82,93,4,Active
8,1009,Karan Malhotra,35,Male,Finance,Mumbai,10,90000,94,91,7,Active
9,1010,Meera Shah,31,Female,IT,Bhopal,7,78000,89,96,6,Active

In [ ]:
df.loc[5:10]

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
5,1006,Neha Gupta,27,Female,IT,Indore,4,62000,91,97,5,Active
6,1007,Rohan Mehta,29,Male,HR,Delhi,6,58000,69,78,3,Inactive
7,1008,Isha Kapoor,26,Female,Marketing,Pune,3,50000,82,93,4,Active
8,1009,Karan Malhotra,35,Male,Finance,Mumbai,10,90000,94,91,7,Active
9,1010,Meera Shah,31,Female,IT,Bhopal,7,78000,89,96,6,Active
10,1011,Aditya Rao,23,Male,Sales,Indore,1,38000,65,74,2,Inactive

In [ ]:
df.iloc[0:6,0:7]

   Employee_ID          Name  Age  Gender Department    City  Experience
0         1001  Aarav Sharma   25    Male         IT  Indore           2
1         1002   Priya Singh   28  Female         HR  Bhopal           5
2         1003   Rahul Verma   30    Male    Finance  Indore           7
3         1004  Ananya Patel   24  Female         IT    Pune           1
4         1005  Vikram Joshi   32    Male      Sales  Mumbai           8
5         1006    Neha Gupta   27  Female         IT  Indore           4

In [ ]:
df[df["Salary"]>=50000]

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
1,1002,Priya Singh,28,Female,HR,Bhopal,5,55000,85,95,4,Active
2,1003,Rahul Verma,30,Male,Finance,Indore,7,72000,88,89,5,Active
4,1005,Vikram Joshi,32,Male,Sales,Mumbai,8,68000,76,84,6,Active
5,1006,Neha Gupta,27,Female,IT,Indore,4,62000,91,97,5,Active
6,1007,Rohan Mehta,29,Male,HR,Delhi,6,58000,69,78,3,Inactive
7,1008,Isha Kapoor,26,Female,Marketing,Pune,3,50000,82,93,4,Active
8,1009,Karan Malhotra,35,Male,Finance,Mumbai,10,90000,94,91,7,Active
9,1010,Meera Shah,31,Female,IT,Bhopal,7,78000,89,96,6,Active
11,1012,Sneha Jain,28,Female,Marketing,Delhi,5,61000,87,88,5,Active
12,1013,Arjun Nair,33,Male,IT,Pune,9,85000,93,94,7,Active
14,1015,Manish Yadav,37,Male,Finance,Delhi,12,98000,90,87,8,Active
15,1016,Pooja Agarwal,29,Female,Sales,Mumbai,6,64000,81,90,5,Active
17,1018,Riya Das,32,Female,IT,Delhi,8,82000,95,98,7,Active
18,1019,Mohit Soni,27,Male,Sales,Pune,4,52000,74,85,4,Active
19,1020,Tanya Roy,30,Female,Finance,Bhopal,7,76000,86,93,6,Active

# **BASICS ANALYSIS**

In [ ]:
df["Salary"].mean()

np.float64(63250.0)

In [ ]:
df["Salary"].max()

98000

In [ ]:
df["Salary"].min()

38000

In [ ]:
df["Age"].mean()

np.float64(28.8)

In [ ]:
df["Experience"].mean()

np.float64(5.5)

In [ ]:
df["Performance_Score"].mean()

np.float64(82.0)

In [ ]:
df["Attendance"].max()

98

In [ ]:
df["Projects"].max()

8

# **FILTERING**

In [ ]:
df[df["Department"] == "IT"]

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
0,1001,Aarav Sharma,25,Male,IT,Indore,2,45000,78,92,3,Active
3,1004,Ananya Patel,24,Female,IT,Pune,1,40000,72,90,2,Active
5,1006,Neha Gupta,27,Female,IT,Indore,4,62000,91,97,5,Active
9,1010,Meera Shah,31,Female,IT,Bhopal,7,78000,89,96,6,Active
12,1013,Arjun Nair,33,Male,IT,Pune,9,85000,93,94,7,Active
17,1018,Riya Das,32,Female,IT,Delhi,8,82000,95,98,7,Active

In [ ]:
df[df["City"] == "Indore"]

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
0,1001,Aarav Sharma,25,Male,IT,Indore,2,45000,78,92,3,Active
2,1003,Rahul Verma,30,Male,Finance,Indore,7,72000,88,89,5,Active
5,1006,Neha Gupta,27,Female,IT,Indore,4,62000,91,97,5,Active
10,1011,Aditya Rao,23,Male,Sales,Indore,1,38000,65,74,2,Inactive
16,1017,Sahil Khan,24,Male,Marketing,Indore,2,43000,70,82,3,Active

In [ ]:
df[df["Salary"]>60000]

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
2,1003,Rahul Verma,30,Male,Finance,Indore,7,72000,88,89,5,Active
4,1005,Vikram Joshi,32,Male,Sales,Mumbai,8,68000,76,84,6,Active
5,1006,Neha Gupta,27,Female,IT,Indore,4,62000,91,97,5,Active
8,1009,Karan Malhotra,35,Male,Finance,Mumbai,10,90000,94,91,7,Active
9,1010,Meera Shah,31,Female,IT,Bhopal,7,78000,89,96,6,Active
11,1012,Sneha Jain,28,Female,Marketing,Delhi,5,61000,87,88,5,Active
12,1013,Arjun Nair,33,Male,IT,Pune,9,85000,93,94,7,Active
14,1015,Manish Yadav,37,Male,Finance,Delhi,12,98000,90,87,8,Active
15,1016,Pooja Agarwal,29,Female,Sales,Mumbai,6,64000,81,90,5,Active
17,1018,Riya Das,32,Female,IT,Delhi,8,82000,95,98,7,Active
19,1020,Tanya Roy,30,Female,Finance,Bhopal,7,76000,86,93,6,Active

In [ ]:
df[df["Experience"]>5]

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
2,1003,Rahul Verma,30,Male,Finance,Indore,7,72000,88,89,5,Active
4,1005,Vikram Joshi,32,Male,Sales,Mumbai,8,68000,76,84,6,Active
6,1007,Rohan Mehta,29,Male,HR,Delhi,6,58000,69,78,3,Inactive
8,1009,Karan Malhotra,35,Male,Finance,Mumbai,10,90000,94,91,7,Active
9,1010,Meera Shah,31,Female,IT,Bhopal,7,78000,89,96,6,Active
12,1013,Arjun Nair,33,Male,IT,Pune,9,85000,93,94,7,Active
14,1015,Manish Yadav,37,Male,Finance,Delhi,12,98000,90,87,8,Active
15,1016,Pooja Agarwal,29,Female,Sales,Mumbai,6,64000,81,90,5,Active
17,1018,Riya Das,32,Female,IT,Delhi,8,82000,95,98,7,Active
19,1020,Tanya Roy,30,Female,Finance,Bhopal,7,76000,86,93,6,Active

In [ ]:
df[df["Performance_Score"]<85]

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
0,1001,Aarav Sharma,25,Male,IT,Indore,2,45000,78,92,3,Active
3,1004,Ananya Patel,24,Female,IT,Pune,1,40000,72,90,2,Active
4,1005,Vikram Joshi,32,Male,Sales,Mumbai,8,68000,76,84,6,Active
6,1007,Rohan Mehta,29,Male,HR,Delhi,6,58000,69,78,3,Inactive
7,1008,Isha Kapoor,26,Female,Marketing,Pune,3,50000,82,93,4,Active
10,1011,Aditya Rao,23,Male,Sales,Indore,1,38000,65,74,2,Inactive
13,1014,Kavya Mishra,26,Female,HR,Bhopal,3,48000,75,86,3,Active
15,1016,Pooja Agarwal,29,Female,Sales,Mumbai,6,64000,81,90,5,Active
16,1017,Sahil Khan,24,Male,Marketing,Indore,2,43000,70,82,3,Active
18,1019,Mohit Soni,27,Male,Sales,Pune,4,52000,74,85,4,Active

In [ ]:
df[df["Gender"] == "Female"]

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
1,1002,Priya Singh,28,Female,HR,Bhopal,5,55000,85,95,4,Active
3,1004,Ananya Patel,24,Female,IT,Pune,1,40000,72,90,2,Active
5,1006,Neha Gupta,27,Female,IT,Indore,4,62000,91,97,5,Active
7,1008,Isha Kapoor,26,Female,Marketing,Pune,3,50000,82,93,4,Active
9,1010,Meera Shah,31,Female,IT,Bhopal,7,78000,89,96,6,Active
11,1012,Sneha Jain,28,Female,Marketing,Delhi,5,61000,87,88,5,Active
13,1014,Kavya Mishra,26,Female,HR,Bhopal,3,48000,75,86,3,Active
15,1016,Pooja Agarwal,29,Female,Sales,Mumbai,6,64000,81,90,5,Active
17,1018,Riya Das,32,Female,IT,Delhi,8,82000,95,98,7,Active
19,1020,Tanya Roy,30,Female,Finance,Bhopal,7,76000,86,93,6,Active

In [ ]:
df[df["Status"] == "Inactive"]

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
6,1007,Rohan Mehta,29,Male,HR,Delhi,6,58000,69,78,3,Inactive
10,1011,Aditya Rao,23,Male,Sales,Indore,1,38000,65,74,2,Inactive

# **MULTIPLE CONDITIONS**

In [ ]:
df[(df["Department"] == "IT") & (df["Salary"]>60000)]

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
5,1006,Neha Gupta,27,Female,IT,Indore,4,62000,91,97,5,Active
9,1010,Meera Shah,31,Female,IT,Bhopal,7,78000,89,96,6,Active
12,1013,Arjun Nair,33,Male,IT,Pune,9,85000,93,94,7,Active
17,1018,Riya Das,32,Female,IT,Delhi,8,82000,95,98,7,Active

In [ ]:
df[(df["Experience"]>5)&(df["Performance_Score"]>85)]

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
2,1003,Rahul Verma,30,Male,Finance,Indore,7,72000,88,89,5,Active
8,1009,Karan Malhotra,35,Male,Finance,Mumbai,10,90000,94,91,7,Active
9,1010,Meera Shah,31,Female,IT,Bhopal,7,78000,89,96,6,Active
12,1013,Arjun Nair,33,Male,IT,Pune,9,85000,93,94,7,Active
14,1015,Manish Yadav,37,Male,Finance,Delhi,12,98000,90,87,8,Active
17,1018,Riya Das,32,Female,IT,Delhi,8,82000,95,98,7,Active
19,1020,Tanya Roy,30,Female,Finance,Bhopal,7,76000,86,93,6,Active

In [ ]:
df[(df["Salary"]>70000)|(df["Performance_Score"]>90)]

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
2,1003,Rahul Verma,30,Male,Finance,Indore,7,72000,88,89,5,Active
5,1006,Neha Gupta,27,Female,IT,Indore,4,62000,91,97,5,Active
8,1009,Karan Malhotra,35,Male,Finance,Mumbai,10,90000,94,91,7,Active
9,1010,Meera Shah,31,Female,IT,Bhopal,7,78000,89,96,6,Active
12,1013,Arjun Nair,33,Male,IT,Pune,9,85000,93,94,7,Active
14,1015,Manish Yadav,37,Male,Finance,Delhi,12,98000,90,87,8,Active
17,1018,Riya Das,32,Female,IT,Delhi,8,82000,95,98,7,Active
19,1020,Tanya Roy,30,Female,Finance,Bhopal,7,76000,86,93,6,Active

In [ ]:
df[(df["City"] == "Indore") & (df["Attendance"]>90)]

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
0,1001,Aarav Sharma,25,Male,IT,Indore,2,45000,78,92,3,Active
5,1006,Neha Gupta,27,Female,IT,Indore,4,62000,91,97,5,Active

In [ ]:
df[(df["Status"] == "Active") & (df["Performance_Score"]<75)]

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
3,1004,Ananya Patel,24,Female,IT,Pune,1,40000,72,90,2,Active
16,1017,Sahil Khan,24,Male,Marketing,Indore,2,43000,70,82,3,Active
18,1019,Mohit Soni,27,Male,Sales,Pune,4,52000,74,85,4,Active

In [ ]:
df[(df["Projects"] <= 5) & (df["Attendance"]>90)]

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
0,1001,Aarav Sharma,25,Male,IT,Indore,2,45000,78,92,3,Active
1,1002,Priya Singh,28,Female,HR,Bhopal,5,55000,85,95,4,Active
5,1006,Neha Gupta,27,Female,IT,Indore,4,62000,91,97,5,Active
7,1008,Isha Kapoor,26,Female,Marketing,Pune,3,50000,82,93,4,Active

# **SORTING**

In [ ]:
df.sort_values("Salary", ascending = False)

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
14,1015,Manish Yadav,37,Male,Finance,Delhi,12,98000,90,87,8,Active
8,1009,Karan Malhotra,35,Male,Finance,Mumbai,10,90000,94,91,7,Active
12,1013,Arjun Nair,33,Male,IT,Pune,9,85000,93,94,7,Active
17,1018,Riya Das,32,Female,IT,Delhi,8,82000,95,98,7,Active
9,1010,Meera Shah,31,Female,IT,Bhopal,7,78000,89,96,6,Active
19,1020,Tanya Roy,30,Female,Finance,Bhopal,7,76000,86,93,6,Active
2,1003,Rahul Verma,30,Male,Finance,Indore,7,72000,88,89,5,Active
4,1005,Vikram Joshi,32,Male,Sales,Mumbai,8,68000,76,84,6,Active
15,1016,Pooja Agarwal,29,Female,Sales,Mumbai,6,64000,81,90,5,Active
5,1006,Neha Gupta,27,Female,IT,Indore,4,62000,91,97,5,Active
11,1012,Sneha Jain,28,Female,Marketing,Delhi,5,61000,87,88,5,Active
6,1007,Rohan Mehta,29,Male,HR,Delhi,6,58000,69,78,3,Inactive
1,1002,Priya Singh,28,Female,HR,Bhopal,5,55000,85,95,4,Active
18,1019,Mohit Soni,27,Male,Sales,Pune,4,52000,74,85,4,Active
7,1008,Isha Kapoor,26,Female,Marketing,Pune,3,50000,82,93,4,Active
13,1014,Kavya Mishra,26,Female,HR,Bhopal,3,48000,75,86,3,Active
0,1001,Aarav Sharma,25,Male,IT,Indore,2,45000,78,92,3,Active
16,1017,Sahil Khan,24,Male,Marketing,Indore,2,43000,70,82,3,Active
3,1004,Ananya Patel,24,Female,IT,Pune,1,40000,72,90,2,Active
10,1011,Aditya Rao,23,Male,Sales,Indore,1,38000,65,74,2,Inactive

In [ ]:
df.sort_values("Salary")

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
10,1011,Aditya Rao,23,Male,Sales,Indore,1,38000,65,74,2,Inactive
3,1004,Ananya Patel,24,Female,IT,Pune,1,40000,72,90,2,Active
16,1017,Sahil Khan,24,Male,Marketing,Indore,2,43000,70,82,3,Active
0,1001,Aarav Sharma,25,Male,IT,Indore,2,45000,78,92,3,Active
13,1014,Kavya Mishra,26,Female,HR,Bhopal,3,48000,75,86,3,Active
7,1008,Isha Kapoor,26,Female,Marketing,Pune,3,50000,82,93,4,Active
18,1019,Mohit Soni,27,Male,Sales,Pune,4,52000,74,85,4,Active
1,1002,Priya Singh,28,Female,HR,Bhopal,5,55000,85,95,4,Active
6,1007,Rohan Mehta,29,Male,HR,Delhi,6,58000,69,78,3,Inactive
11,1012,Sneha Jain,28,Female,Marketing,Delhi,5,61000,87,88,5,Active
5,1006,Neha Gupta,27,Female,IT,Indore,4,62000,91,97,5,Active
15,1016,Pooja Agarwal,29,Female,Sales,Mumbai,6,64000,81,90,5,Active
4,1005,Vikram Joshi,32,Male,Sales,Mumbai,8,68000,76,84,6,Active
2,1003,Rahul Verma,30,Male,Finance,Indore,7,72000,88,89,5,Active
19,1020,Tanya Roy,30,Female,Finance,Bhopal,7,76000,86,93,6,Active
9,1010,Meera Shah,31,Female,IT,Bhopal,7,78000,89,96,6,Active
17,1018,Riya Das,32,Female,IT,Delhi,8,82000,95,98,7,Active
12,1013,Arjun Nair,33,Male,IT,Pune,9,85000,93,94,7,Active
8,1009,Karan Malhotra,35,Male,Finance,Mumbai,10,90000,94,91,7,Active
14,1015,Manish Yadav,37,Male,Finance,Delhi,12,98000,90,87,8,Active

In [ ]:
df.sort_values("Experience")

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
3,1004,Ananya Patel,24,Female,IT,Pune,1,40000,72,90,2,Active
10,1011,Aditya Rao,23,Male,Sales,Indore,1,38000,65,74,2,Inactive
0,1001,Aarav Sharma,25,Male,IT,Indore,2,45000,78,92,3,Active
16,1017,Sahil Khan,24,Male,Marketing,Indore,2,43000,70,82,3,Active
13,1014,Kavya Mishra,26,Female,HR,Bhopal,3,48000,75,86,3,Active
7,1008,Isha Kapoor,26,Female,Marketing,Pune,3,50000,82,93,4,Active
18,1019,Mohit Soni,27,Male,Sales,Pune,4,52000,74,85,4,Active
5,1006,Neha Gupta,27,Female,IT,Indore,4,62000,91,97,5,Active
1,1002,Priya Singh,28,Female,HR,Bhopal,5,55000,85,95,4,Active
11,1012,Sneha Jain,28,Female,Marketing,Delhi,5,61000,87,88,5,Active
6,1007,Rohan Mehta,29,Male,HR,Delhi,6,58000,69,78,3,Inactive
15,1016,Pooja Agarwal,29,Female,Sales,Mumbai,6,64000,81,90,5,Active
9,1010,Meera Shah,31,Female,IT,Bhopal,7,78000,89,96,6,Active
19,1020,Tanya Roy,30,Female,Finance,Bhopal,7,76000,86,93,6,Active
2,1003,Rahul Verma,30,Male,Finance,Indore,7,72000,88,89,5,Active
4,1005,Vikram Joshi,32,Male,Sales,Mumbai,8,68000,76,84,6,Active
17,1018,Riya Das,32,Female,IT,Delhi,8,82000,95,98,7,Active
12,1013,Arjun Nair,33,Male,IT,Pune,9,85000,93,94,7,Active
8,1009,Karan Malhotra,35,Male,Finance,Mumbai,10,90000,94,91,7,Active
14,1015,Manish Yadav,37,Male,Finance,Delhi,12,98000,90,87,8,Active

In [ ]:
df.sort_values("Attendance" , ascending = False)

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
17,1018,Riya Das,32,Female,IT,Delhi,8,82000,95,98,7,Active
5,1006,Neha Gupta,27,Female,IT,Indore,4,62000,91,97,5,Active
9,1010,Meera Shah,31,Female,IT,Bhopal,7,78000,89,96,6,Active
1,1002,Priya Singh,28,Female,HR,Bhopal,5,55000,85,95,4,Active
12,1013,Arjun Nair,33,Male,IT,Pune,9,85000,93,94,7,Active
7,1008,Isha Kapoor,26,Female,Marketing,Pune,3,50000,82,93,4,Active
19,1020,Tanya Roy,30,Female,Finance,Bhopal,7,76000,86,93,6,Active
0,1001,Aarav Sharma,25,Male,IT,Indore,2,45000,78,92,3,Active
8,1009,Karan Malhotra,35,Male,Finance,Mumbai,10,90000,94,91,7,Active
3,1004,Ananya Patel,24,Female,IT,Pune,1,40000,72,90,2,Active
15,1016,Pooja Agarwal,29,Female,Sales,Mumbai,6,64000,81,90,5,Active
2,1003,Rahul Verma,30,Male,Finance,Indore,7,72000,88,89,5,Active
11,1012,Sneha Jain,28,Female,Marketing,Delhi,5,61000,87,88,5,Active
14,1015,Manish Yadav,37,Male,Finance,Delhi,12,98000,90,87,8,Active
13,1014,Kavya Mishra,26,Female,HR,Bhopal,3,48000,75,86,3,Active
18,1019,Mohit Soni,27,Male,Sales,Pune,4,52000,74,85,4,Active
4,1005,Vikram Joshi,32,Male,Sales,Mumbai,8,68000,76,84,6,Active
16,1017,Sahil Khan,24,Male,Marketing,Indore,2,43000,70,82,3,Active
6,1007,Rohan Mehta,29,Male,HR,Delhi,6,58000,69,78,3,Inactive
10,1011,Aditya Rao,23,Male,Sales,Indore,1,38000,65,74,2,Inactive

In [ ]:
df.sort_values(["Department" ,"Salary"])

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
2,1003,Rahul Verma,30,Male,Finance,Indore,7,72000,88,89,5,Active
19,1020,Tanya Roy,30,Female,Finance,Bhopal,7,76000,86,93,6,Active
8,1009,Karan Malhotra,35,Male,Finance,Mumbai,10,90000,94,91,7,Active
14,1015,Manish Yadav,37,Male,Finance,Delhi,12,98000,90,87,8,Active
13,1014,Kavya Mishra,26,Female,HR,Bhopal,3,48000,75,86,3,Active
1,1002,Priya Singh,28,Female,HR,Bhopal,5,55000,85,95,4,Active
6,1007,Rohan Mehta,29,Male,HR,Delhi,6,58000,69,78,3,Inactive
3,1004,Ananya Patel,24,Female,IT,Pune,1,40000,72,90,2,Active
0,1001,Aarav Sharma,25,Male,IT,Indore,2,45000,78,92,3,Active
5,1006,Neha Gupta,27,Female,IT,Indore,4,62000,91,97,5,Active
9,1010,Meera Shah,31,Female,IT,Bhopal,7,78000,89,96,6,Active
17,1018,Riya Das,32,Female,IT,Delhi,8,82000,95,98,7,Active
12,1013,Arjun Nair,33,Male,IT,Pune,9,85000,93,94,7,Active
16,1017,Sahil Khan,24,Male,Marketing,Indore,2,43000,70,82,3,Active
7,1008,Isha Kapoor,26,Female,Marketing,Pune,3,50000,82,93,4,Active
11,1012,Sneha Jain,28,Female,Marketing,Delhi,5,61000,87,88,5,Active
10,1011,Aditya Rao,23,Male,Sales,Indore,1,38000,65,74,2,Inactive
18,1019,Mohit Soni,27,Male,Sales,Pune,4,52000,74,85,4,Active
15,1016,Pooja Agarwal,29,Female,Sales,Mumbai,6,64000,81,90,5,Active
4,1005,Vikram Joshi,32,Male,Sales,Mumbai,8,68000,76,84,6,Active

# **CREATING NEW COLUMNS**

In [ ]:
df["Annual_Salary"] = df["Salary"] * 12
print(df)

    Employee_ID            Name  Age  Gender Department    City  Experience  \
0          1001    Aarav Sharma   25    Male         IT  Indore           2
1          1002     Priya Singh   28  Female         HR  Bhopal           5
2          1003     Rahul Verma   30    Male    Finance  Indore           7
3          1004    Ananya Patel   24  Female         IT    Pune           1
4          1005    Vikram Joshi   32    Male      Sales  Mumbai           8
5          1006      Neha Gupta   27  Female         IT  Indore           4
6          1007     Rohan Mehta   29    Male         HR   Delhi           6
7          1008     Isha Kapoor   26  Female  Marketing    Pune           3
8          1009  Karan Malhotra   35    Male    Finance  Mumbai          10
9          1010      Meera Shah   31  Female         IT  Bhopal           7
10         1011      Aditya Rao   23    Male      Sales  Indore           1
11         1012      Sneha Jain   28  Female  Marketing   Delhi           5
12         1013      Arjun Nair   33    Male         IT    Pune           9
13         1014    Kavya Mishra   26  Female         HR  Bhopal           3
14         1015    Manish Yadav   37    Male    Finance   Delhi          12
15         1016   Pooja Agarwal   29  Female      Sales  Mumbai           6
16         1017      Sahil Khan   24    Male  Marketing  Indore           2
17         1018        Riya Das   32  Female         IT   Delhi           8
18         1019      Mohit Soni   27    Male      Sales    Pune           4
19         1020       Tanya Roy   30  Female    Finance  Bhopal           7

    Salary  Performance_Score  Attendance  Projects    Status  Annual_Salary
0    45000                 78          92         3    Active         540000
1    55000                 85          95         4    Active         660000
2    72000                 88          89         5    Active         864000
3    40000                 72          90         2    Active         480000
4    68000                 76          84         6    Active         816000
5    62000                 91          97         5    Active         744000
6    58000                 69          78         3  Inactive         696000
7    50000                 82          93         4    Active         600000
8    90000                 94          91         7    Active        1080000
9    78000                 89          96         6    Active         936000
10   38000                 65          74         2  Inactive         456000
11   61000                 87          88         5    Active         732000
12   85000                 93          94         7    Active        1020000
13   48000                 75          86         3    Active         576000
14   98000                 90          87         8    Active        1176000
15   64000                 81          90         5    Active         768000
16   43000                 70          82         3    Active         516000
17   82000                 95          98         7    Active         984000
18   52000                 74          85         4    Active         624000
19   76000                 86          93         6    Active         912000

In [ ]:
df["Performance_Level"] = df["Performance_Score"].apply(
    lambda x: "Excellent" if x >= 90
    else "Good" if x >= 80
    else "Needs Improvement"
)
print(df)

    Employee_ID            Name  Age  Gender Department    City  Experience  \
0          1001    Aarav Sharma   25    Male         IT  Indore           2
1          1002     Priya Singh   28  Female         HR  Bhopal           5
2          1003     Rahul Verma   30    Male    Finance  Indore           7
3          1004    Ananya Patel   24  Female         IT    Pune           1
4          1005    Vikram Joshi   32    Male      Sales  Mumbai           8
5          1006      Neha Gupta   27  Female         IT  Indore           4
6          1007     Rohan Mehta   29    Male         HR   Delhi           6
7          1008     Isha Kapoor   26  Female  Marketing    Pune           3
8          1009  Karan Malhotra   35    Male    Finance  Mumbai          10
9          1010      Meera Shah   31  Female         IT  Bhopal           7
10         1011      Aditya Rao   23    Male      Sales  Indore           1
11         1012      Sneha Jain   28  Female  Marketing   Delhi           5
12         1013      Arjun Nair   33    Male         IT    Pune           9
13         1014    Kavya Mishra   26  Female         HR  Bhopal           3
14         1015    Manish Yadav   37    Male    Finance   Delhi          12
15         1016   Pooja Agarwal   29  Female      Sales  Mumbai           6
16         1017      Sahil Khan   24    Male  Marketing  Indore           2
17         1018        Riya Das   32  Female         IT   Delhi           8
18         1019      Mohit Soni   27    Male      Sales    Pune           4
19         1020       Tanya Roy   30  Female    Finance  Bhopal           7

    Salary  Performance_Score  Attendance  Projects    Status  Annual_Salary  \
0    45000                 78          92         3    Active         540000
1    55000                 85          95         4    Active         660000
2    72000                 88          89         5    Active         864000
3    40000                 72          90         2    Active         480000
4    68000                 76          84         6    Active         816000
5    62000                 91          97         5    Active         744000
6    58000                 69          78         3  Inactive         696000
7    50000                 82          93         4    Active         600000
8    90000                 94          91         7    Active        1080000
9    78000                 89          96         6    Active         936000
10   38000                 65          74         2  Inactive         456000
11   61000                 87          88         5    Active         732000
12   85000                 93          94         7    Active        1020000
13   48000                 75          86         3    Active         576000
14   98000                 90          87         8    Active        1176000
15   64000                 81          90         5    Active         768000
16   43000                 70          82         3    Active         516000
17   82000                 95          98         7    Active         984000
18   52000                 74          85         4    Active         624000
19   76000                 86          93         6    Active         912000

    Performance_Level
0   Needs Improvement
1                Good
2                Good
3   Needs Improvement
4   Needs Improvement
5           Excellent
6   Needs Improvement
7                Good
8           Excellent
9                Good
10  Needs Improvement
11               Good
12          Excellent
13  Needs Improvement
14          Excellent
15               Good
16  Needs Improvement
17          Excellent
18  Needs Improvement
19               Good

In [ ]:
df["Experience_Level"] = df["Experience"].apply(
    lambda x:"Senior" if x>=8
    else "Mid-Level" if x>=4
    else "Junior"
    )
print(df)

    Employee_ID            Name  Age  Gender Department    City  Experience  \
0          1001    Aarav Sharma   25    Male         IT  Indore           2
1          1002     Priya Singh   28  Female         HR  Bhopal           5
2          1003     Rahul Verma   30    Male    Finance  Indore           7
3          1004    Ananya Patel   24  Female         IT    Pune           1
4          1005    Vikram Joshi   32    Male      Sales  Mumbai           8
5          1006      Neha Gupta   27  Female         IT  Indore           4
6          1007     Rohan Mehta   29    Male         HR   Delhi           6
7          1008     Isha Kapoor   26  Female  Marketing    Pune           3
8          1009  Karan Malhotra   35    Male    Finance  Mumbai          10
9          1010      Meera Shah   31  Female         IT  Bhopal           7
10         1011      Aditya Rao   23    Male      Sales  Indore           1
11         1012      Sneha Jain   28  Female  Marketing   Delhi           5
12         1013      Arjun Nair   33    Male         IT    Pune           9
13         1014    Kavya Mishra   26  Female         HR  Bhopal           3
14         1015    Manish Yadav   37    Male    Finance   Delhi          12
15         1016   Pooja Agarwal   29  Female      Sales  Mumbai           6
16         1017      Sahil Khan   24    Male  Marketing  Indore           2
17         1018        Riya Das   32  Female         IT   Delhi           8
18         1019      Mohit Soni   27    Male      Sales    Pune           4
19         1020       Tanya Roy   30  Female    Finance  Bhopal           7

    Salary  Performance_Score  Attendance  Projects    Status  Annual_Salary  \
0    45000                 78          92         3    Active         540000
1    55000                 85          95         4    Active         660000
2    72000                 88          89         5    Active         864000
3    40000                 72          90         2    Active         480000
4    68000                 76          84         6    Active         816000
5    62000                 91          97         5    Active         744000
6    58000                 69          78         3  Inactive         696000
7    50000                 82          93         4    Active         600000
8    90000                 94          91         7    Active        1080000
9    78000                 89          96         6    Active         936000
10   38000                 65          74         2  Inactive         456000
11   61000                 87          88         5    Active         732000
12   85000                 93          94         7    Active        1020000
13   48000                 75          86         3    Active         576000
14   98000                 90          87         8    Active        1176000
15   64000                 81          90         5    Active         768000
16   43000                 70          82         3    Active         516000
17   82000                 95          98         7    Active         984000
18   52000                 74          85         4    Active         624000
19   76000                 86          93         6    Active         912000

    Performance_Level Experience_Level
0   Needs Improvement           Junior
1                Good        Mid-Level
2                Good        Mid-Level
3   Needs Improvement           Junior
4   Needs Improvement           Senior
5           Excellent        Mid-Level
6   Needs Improvement        Mid-Level
7                Good           Junior
8           Excellent           Senior
9                Good        Mid-Level
10  Needs Improvement           Junior
11               Good        Mid-Level
12          Excellent           Senior
13  Needs Improvement           Junior
14          Excellent           Senior
15               Good        Mid-Level
16  Needs Improvement           Junior
17          Excellent           Senior
18  Needs Improvement        Mid-Level
19               Good        Mid-Level

In [ ]:
df["Attendance_Status"] = df["Attendance"].apply(
    lambda x:"Good" if x >= 90
    else "Low"
)
print(df)

    Employee_ID            Name  Age  Gender Department    City  Experience  \
0          1001    Aarav Sharma   25    Male         IT  Indore           2
1          1002     Priya Singh   28  Female         HR  Bhopal           5
2          1003     Rahul Verma   30    Male    Finance  Indore           7
3          1004    Ananya Patel   24  Female         IT    Pune           1
4          1005    Vikram Joshi   32    Male      Sales  Mumbai           8
5          1006      Neha Gupta   27  Female         IT  Indore           4
6          1007     Rohan Mehta   29    Male         HR   Delhi           6
7          1008     Isha Kapoor   26  Female  Marketing    Pune           3
8          1009  Karan Malhotra   35    Male    Finance  Mumbai          10
9          1010      Meera Shah   31  Female         IT  Bhopal           7
10         1011      Aditya Rao   23    Male      Sales  Indore           1
11         1012      Sneha Jain   28  Female  Marketing   Delhi           5
12         1013      Arjun Nair   33    Male         IT    Pune           9
13         1014    Kavya Mishra   26  Female         HR  Bhopal           3
14         1015    Manish Yadav   37    Male    Finance   Delhi          12
15         1016   Pooja Agarwal   29  Female      Sales  Mumbai           6
16         1017      Sahil Khan   24    Male  Marketing  Indore           2
17         1018        Riya Das   32  Female         IT   Delhi           8
18         1019      Mohit Soni   27    Male      Sales    Pune           4
19         1020       Tanya Roy   30  Female    Finance  Bhopal           7

    Salary  Performance_Score  Attendance  Projects    Status  Annual_Salary  \
0    45000                 78          92         3    Active         540000
1    55000                 85          95         4    Active         660000
2    72000                 88          89         5    Active         864000
3    40000                 72          90         2    Active         480000
4    68000                 76          84         6    Active         816000
5    62000                 91          97         5    Active         744000
6    58000                 69          78         3  Inactive         696000
7    50000                 82          93         4    Active         600000
8    90000                 94          91         7    Active        1080000
9    78000                 89          96         6    Active         936000
10   38000                 65          74         2  Inactive         456000
11   61000                 87          88         5    Active         732000
12   85000                 93          94         7    Active        1020000
13   48000                 75          86         3    Active         576000
14   98000                 90          87         8    Active        1176000
15   64000                 81          90         5    Active         768000
16   43000                 70          82         3    Active         516000
17   82000                 95          98         7    Active         984000
18   52000                 74          85         4    Active         624000
19   76000                 86          93         6    Active         912000

    Performance_Level Experience_Level Attendance_Status
0   Needs Improvement           Junior              Good
1                Good        Mid-Level              Good
2                Good        Mid-Level               Low
3   Needs Improvement           Junior              Good
4   Needs Improvement           Senior               Low
5           Excellent        Mid-Level              Good
6   Needs Improvement        Mid-Level               Low
7                Good           Junior              Good
8           Excellent           Senior              Good
9                Good        Mid-Level              Good
10  Needs Improvement           Junior               Low
11               Good        Mid-Level               Low
12          Excellent           Senior              Good
13  Needs Improvement           Junior               Low
14          Excellent           Senior               Low
15               Good        Mid-Level              Good
16  Needs Improvement           Junior               Low
17          Excellent           Senior              Good
18  Needs Improvement        Mid-Level               Low
19               Good        Mid-Level              Good

# **VALUE COUNTS & UNIQUE VALUES**

In [ ]:
df["Department"].value_counts()

Department
IT           6
Finance      4
Sales        4
HR           3
Marketing    3
Name: count, dtype: int64

In [ ]:
df["City"].value_counts()

City
Indore    5
Bhopal    4
Pune      4
Delhi     4
Mumbai    3
Name: count, dtype: int64

In [ ]:
df["Gender"].value_counts()

Gender
Male      10
Female    10
Name: count, dtype: int64

In [ ]:
df["Status"].value_counts()

Status
Active      18
Inactive     2
Name: count, dtype: int64

In [ ]:
df["Department"].unique()

array(['IT', 'HR', 'Finance', 'Sales', 'Marketing'], dtype=object)

In [ ]:
df["City"].unique()

array(['Indore', 'Bhopal', 'Pune', 'Mumbai', 'Delhi'], dtype=object)

In [ ]:
df["Department"].nunique()

5

# **GROUPBY ANALYSIS**

In [ ]:
df.groupby("Department")["Salary"].mean()

Department
Finance      84000.000000
HR           53666.666667
IT           65333.333333
Marketing    51333.333333
Sales        55500.000000
Name: Salary, dtype: float64

In [ ]:
df.groupby("Department")["Performance_Score"].mean()

Department
Finance      89.500000
HR           76.333333
IT           86.333333
Marketing    79.666667
Sales        74.000000
Name: Performance_Score, dtype: float64

In [ ]:
df.groupby("Department")["Attendance"].mean()

Department
Finance      90.000000
HR           86.333333
IT           94.500000
Marketing    87.666667
Sales        83.250000
Name: Attendance, dtype: float64

In [ ]:
df.groupby("Department")["Attendance"].mean()

Department
Finance      90.000000
HR           86.333333
IT           94.500000
Marketing    87.666667
Sales        83.250000
Name: Attendance, dtype: float64

In [ ]:
df.groupby("Department")["Experience"].mean()

Department
Finance      9.000000
HR           4.666667
IT           5.166667
Marketing    3.333333
Sales        4.750000
Name: Experience, dtype: float64

In [ ]:
df.groupby("Department")["Employee_ID"].count()

Department
Finance      4
HR           3
IT           6
Marketing    3
Sales        4
Name: Employee_ID, dtype: int64

In [ ]:
df.groupby("City")["Salary"].mean()

City
Bhopal    64250.0
Delhi     74750.0
Indore    52000.0
Mumbai    74000.0
Pune      56750.0
Name: Salary, dtype: float64

In [ ]:
df.groupby("Gender")["Performance_Score"].mean()

Gender
Female    84.3
Male      79.7
Name: Performance_Score, dtype: float64

# **INTERMEDIATE ANALYSIS**

In [ ]:
top_5 = df.sort_values("Salary", ascending=False)[["Name", "Salary"]].head(5)

print(top_5)

              Name  Salary
14    Manish Yadav   98000
8   Karan Malhotra   90000
12      Arjun Nair   85000
17        Riya Das   82000
9       Meera Shah   78000

In [ ]:
top_5 = df.sort_values("Performance_Score", ascending= False)[["Name","Performance_Score"]].head(5)
print(top_5)

              Name  Performance_Score
17        Riya Das                 95
8   Karan Malhotra                 94
12      Arjun Nair                 93
5       Neha Gupta                 91
14    Manish Yadav                 90

In [ ]:
bottom_5 = df.sort_values("Performance_Score", ascending= False)[["Name","Performance_Score"]].tail(5)
print(bottom_5)

            Name  Performance_Score
18    Mohit Soni                 74
3   Ananya Patel                 72
16    Sahil Khan                 70
6    Rohan Mehta                 69
10    Aditya Rao                 65

In [ ]:
top = df.sort_values("Salary",ascending = False)[["Name","Salary"]].head(1)
print(top)

            Name  Salary
14  Manish Yadav   98000

In [ ]:
top = df.sort_values("Performance_Score",ascending = False)[["Name","Performance_Score"]].head(1)
print(top)

        Name  Performance_Score
17  Riya Das                 95

In [ ]:
top = df.sort_values("Experience",ascending = False)[["Name","Experience"]].head(1)
print(top)

            Name  Experience
14  Manish Yadav          12

In [ ]:
avg_salary=df["Salary"].mean()
above_avg = df[df["Salary"]>avg_salary]
print(above_avg)

    Employee_ID            Name  Age  Gender Department    City  Experience  \
2          1003     Rahul Verma   30    Male    Finance  Indore           7
4          1005    Vikram Joshi   32    Male      Sales  Mumbai           8
8          1009  Karan Malhotra   35    Male    Finance  Mumbai          10
9          1010      Meera Shah   31  Female         IT  Bhopal           7
12         1013      Arjun Nair   33    Male         IT    Pune           9
14         1015    Manish Yadav   37    Male    Finance   Delhi          12
15         1016   Pooja Agarwal   29  Female      Sales  Mumbai           6
17         1018        Riya Das   32  Female         IT   Delhi           8
19         1020       Tanya Roy   30  Female    Finance  Bhopal           7

    Salary  Performance_Score  Attendance  Projects  Status
2    72000                 88          89         5  Active
4    68000                 76          84         6  Active
8    90000                 94          91         7  Active
9    78000                 89          96         6  Active
12   85000                 93          94         7  Active
14   98000                 90          87         8  Active
15   64000                 81          90         5  Active
17   82000                 95          98         7  Active
19   76000                 86          93         6  Active

In [4]:
df[df["Performance_Score"]>df["Performance_Score"].mean()]

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
1,1002,Priya Singh,28,Female,HR,Bhopal,5,55000,85,95,4,Active
2,1003,Rahul Verma,30,Male,Finance,Indore,7,72000,88,89,5,Active
5,1006,Neha Gupta,27,Female,IT,Indore,4,62000,91,97,5,Active
8,1009,Karan Malhotra,35,Male,Finance,Mumbai,10,90000,94,91,7,Active
9,1010,Meera Shah,31,Female,IT,Bhopal,7,78000,89,96,6,Active
11,1012,Sneha Jain,28,Female,Marketing,Delhi,5,61000,87,88,5,Active
12,1013,Arjun Nair,33,Male,IT,Pune,9,85000,93,94,7,Active
14,1015,Manish Yadav,37,Male,Finance,Delhi,12,98000,90,87,8,Active
17,1018,Riya Das,32,Female,IT,Delhi,8,82000,95,98,7,Active
19,1020,Tanya Roy,30,Female,Finance,Bhopal,7,76000,86,93,6,Active

# **HR INSIGHTS**

In [6]:
df[df["Performance_Score"]<75]

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
3,1004,Ananya Patel,24,Female,IT,Pune,1,40000,72,90,2,Active
6,1007,Rohan Mehta,29,Male,HR,Delhi,6,58000,69,78,3,Inactive
10,1011,Aditya Rao,23,Male,Sales,Indore,1,38000,65,74,2,Inactive
16,1017,Sahil Khan,24,Male,Marketing,Indore,2,43000,70,82,3,Active
18,1019,Mohit Soni,27,Male,Sales,Pune,4,52000,74,85,4,Active

In [7]:
df[df["Attendance"]<85]

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
4,1005,Vikram Joshi,32,Male,Sales,Mumbai,8,68000,76,84,6,Active
6,1007,Rohan Mehta,29,Male,HR,Delhi,6,58000,69,78,3,Inactive
10,1011,Aditya Rao,23,Male,Sales,Indore,1,38000,65,74,2,Inactive
16,1017,Sahil Khan,24,Male,Marketing,Indore,2,43000,70,82,3,Active

In [9]:
df[(df["Experience"]>5)&(df["Salary"]<60000)]

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
6,1007,Rohan Mehta,29,Male,HR,Delhi,6,58000,69,78,3,Inactive

In [10]:
df[(df["Performance_Score"]>85)&(df["Attendance"]<90)]

,Employee_ID,Name,Age,Gender,Department,City,Experience,Salary,Performance_Score,Attendance,Projects,Status
2,1003,Rahul Verma,30,Male,Finance,Indore,7,72000,88,89,5,Active
11,1012,Sneha Jain,28,Female,Marketing,Delhi,5,61000,87,88,5,Active
14,1015,Manish Yadav,37,Male,Finance,Delhi,12,98000,90,87,8,Active

In [11]:
df.groupby("Department")["Salary"].mean().sort_values(ascending=False)

Department
Finance      84000.000000
IT           65333.333333
Sales        55500.000000
HR           53666.666667
Marketing    51333.333333
Name: Salary, dtype: float64

In [15]:
df.groupby("Department")["Performance_Score"].mean().sort_values(ascending=False)

Department
Finance      89.500000
IT           86.333333
Marketing    79.666667
HR           76.333333
Sales        74.000000
Name: Performance_Score, dtype: float64

In [14]:
df.groupby("Department")["Salary"].max().idxmax()

'Finance'

In [17]:
df.groupby("Department")["Performance_Score"].mean().idxmax()

'Finance'

# **EMPLOYEE REPORT**

In [18]:
import pandas as pd
data = {
    "Employee_ID":[1,2,3,4,5,6,7,8,9,10],
    "Name":["a","b","c","d","e","h","i","j","k","l"],
    "Department": ["IT","HR","sales","systems","marketing","sales","IT","marketing","finance","finance"],
    "Experience":[8,6,5,4,6,7,8,2,3,4],
    "Salary":[20000,30000,40000,50000,60000,60000,50000,55000,55000,70000],
    "Performance_Score":[75,85,90,90,95,80,87,96,90,75],
    "Attendance":[93,98,78,86,87,90,92,89,97,79],
    "Project":[3,4,3,2,5,3,6,4,5,4],
    "Status":["Active","Active","Inactive","Active","Active","Inactive","Active","Active","Inactive","Active"]
}
df = pd.DataFrame(data)
print(df)

   Employee_ID Name Department  Experience  Salary  Performance_Score  \
0            1    a         IT           8   20000                 75
1            2    b         HR           6   30000                 85
2            3    c      sales           5   40000                 90
3            4    d    systems           4   50000                 90
4            5    e  marketing           6   60000                 95
5            6    h      sales           7   60000                 80
6            7    i         IT           8   50000                 87
7            8    j  marketing           2   55000                 96
8            9    k    finance           3   55000                 90
9           10    l    finance           4   70000                 75

   Attendance  Project    Status
0          93        3    Active
1          98        4    Active
2          78        3  Inactive
3          86        2    Active
4          87        5    Active
5          90        3  Inactive
6          92        6    Active
7          89        4    Active
8          97        5  Inactive
9          79        4    Active

In [22]:
df["Annual_Salary"]=df["Salary"]*12
print(df)

   Employee_ID Name Department  Experience  Salary  Performance_Score  \
0            1    a         IT           8   20000                 75
1            2    b         HR           6   30000                 85
2            3    c      sales           5   40000                 90
3            4    d    systems           4   50000                 90
4            5    e  marketing           6   60000                 95
5            6    h      sales           7   60000                 80
6            7    i         IT           8   50000                 87
7            8    j  marketing           2   55000                 96
8            9    k    finance           3   55000                 90
9           10    l    finance           4   70000                 75

   Attendance  Project    Status  Annual_Salary
0          93        3    Active         240000
1          98        4    Active         360000
2          78        3  Inactive         480000
3          86        2    Active         600000
4          87        5    Active         720000
5          90        3  Inactive         720000
6          92        6    Active         600000
7          89        4    Active         660000
8          97        5  Inactive         660000
9          79        4    Active         840000

In [23]:
df["Performance_Level"]=df["Performance_Score"].apply(lambda x:"Excellent" if x>=90
                                                      else "Good" if x>=80
                                                      else "Needs Improvement")
print(df)

   Employee_ID Name Department  Experience  Salary  Performance_Score  \
0            1    a         IT           8   20000                 75
1            2    b         HR           6   30000                 85
2            3    c      sales           5   40000                 90
3            4    d    systems           4   50000                 90
4            5    e  marketing           6   60000                 95
5            6    h      sales           7   60000                 80
6            7    i         IT           8   50000                 87
7            8    j  marketing           2   55000                 96
8            9    k    finance           3   55000                 90
9           10    l    finance           4   70000                 75

   Attendance  Project    Status  Annual_Salary  Performance_Level
0          93        3    Active         240000  Needs Improvement
1          98        4    Active         360000               Good
2          78        3  Inactive         480000          Excellent
3          86        2    Active         600000          Excellent
4          87        5    Active         720000          Excellent
5          90        3  Inactive         720000               Good
6          92        6    Active         600000               Good
7          89        4    Active         660000          Excellent
8          97        5  Inactive         660000          Excellent
9          79        4    Active         840000  Needs Improvement

In [24]:
df["Experience_Level"]=df["Experience"].apply(lambda x:"Senior" if x>=8
                                              else "Mid-Level" if x>=4
                                              else "Junior")
print(df)

   Employee_ID Name Department  Experience  Salary  Performance_Score  \
0            1    a         IT           8   20000                 75
1            2    b         HR           6   30000                 85
2            3    c      sales           5   40000                 90
3            4    d    systems           4   50000                 90
4            5    e  marketing           6   60000                 95
5            6    h      sales           7   60000                 80
6            7    i         IT           8   50000                 87
7            8    j  marketing           2   55000                 96
8            9    k    finance           3   55000                 90
9           10    l    finance           4   70000                 75

   Attendance  Project    Status  Annual_Salary  Performance_Level  \
0          93        3    Active         240000  Needs Improvement
1          98        4    Active         360000               Good
2          78        3  Inactive         480000          Excellent
3          86        2    Active         600000          Excellent
4          87        5    Active         720000          Excellent
5          90        3  Inactive         720000               Good
6          92        6    Active         600000               Good
7          89        4    Active         660000          Excellent
8          97        5  Inactive         660000          Excellent
9          79        4    Active         840000  Needs Improvement

  Experience_Level
0           Senior
1        Mid-Level
2        Mid-Level
3        Mid-Level
4        Mid-Level
5        Mid-Level
6           Senior
7           Junior
8           Junior
9        Mid-Level

In [25]:
df.sort_values(["Performance_Score"], ascending= False)

,Employee_ID,Name,Department,Experience,Salary,Performance_Score,Attendance,Project,Status,Annual_Salary,Performance_Level,Experience_Level
7,8,j,marketing,2,55000,96,89,4,Active,660000,Excellent,Junior
4,5,e,marketing,6,60000,95,87,5,Active,720000,Excellent,Mid-Level
8,9,k,finance,3,55000,90,97,5,Inactive,660000,Excellent,Junior
2,3,c,sales,5,40000,90,78,3,Inactive,480000,Excellent,Mid-Level
3,4,d,systems,4,50000,90,86,2,Active,600000,Excellent,Mid-Level
6,7,i,IT,8,50000,87,92,6,Active,600000,Good,Senior
1,2,b,HR,6,30000,85,98,4,Active,360000,Good,Mid-Level
5,6,h,sales,7,60000,80,90,3,Inactive,720000,Good,Mid-Level
0,1,a,IT,8,20000,75,93,3,Active,240000,Needs Improvement,Senior
9,10,l,finance,4,70000,75,79,4,Active,840000,Needs Improvement,Mid-Level

In [28]:
top_5 = df.sort_values("Performance_Score", ascending=False).head(5)
print(top_5)

   Employee_ID Name Department  Experience  Salary  Performance_Score  \
7            8    j  marketing           2   55000                 96
4            5    e  marketing           6   60000                 95
8            9    k    finance           3   55000                 90
2            3    c      sales           5   40000                 90
3            4    d    systems           4   50000                 90

   Attendance  Project    Status  Annual_Salary Performance_Level  \
7          89        4    Active         660000         Excellent
4          87        5    Active         720000         Excellent
8          97        5  Inactive         660000         Excellent
2          78        3  Inactive         480000         Excellent
3          86        2    Active         600000         Excellent

  Experience_Level
7           Junior
4        Mid-Level
8           Junior
2        Mid-Level
3        Mid-Level

In [31]:
df[df["Performance_Level"]=="Needs Improvement"]

,Employee_ID,Name,Department,Experience,Salary,Performance_Score,Attendance,Project,Status,Annual_Salary,Performance_Level,Experience_Level
0,1,a,IT,8,20000,75,93,3,Active,240000,Needs Improvement,Senior
9,10,l,finance,4,70000,75,79,4,Active,840000,Needs Improvement,Mid-Level

In [32]:
df[df["Attendance"]>90]

,Employee_ID,Name,Department,Experience,Salary,Performance_Score,Attendance,Project,Status,Annual_Salary,Performance_Level,Experience_Level
0,1,a,IT,8,20000,75,93,3,Active,240000,Needs Improvement,Senior
1,2,b,HR,6,30000,85,98,4,Active,360000,Good,Mid-Level
6,7,i,IT,8,50000,87,92,6,Active,600000,Good,Senior
8,9,k,finance,3,55000,90,97,5,Inactive,660000,Excellent,Junior

In [34]:
df.groupby("Department").agg({"Salary":"mean"},{"Performance_Score":"mean"})

             Salary
Department
HR          30000.0
IT          35000.0
finance     62500.0
marketing   57500.0
sales       50000.0
systems     50000.0

In [37]:
df["Performance_Score"].idxmax()

7

In [40]:
strongest = df.groupby('Department')['Performance_Score'].mean().idxmax()

print(strongest)

marketing